import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='Next JS Practice' content='Generated by create next app' />
      </Head>
      <h1>Hello World</h1>
    </div>
  );
}
