import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Practice Next JS</title>
        <meta name='Next JS Practice' content='Generated by create next app' />
      </Head>
      <h1>Hello World</h1>
      <p>practing next js.....</p>
    </div>
  );
}
